[package]
name = "nomad-bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.1" # The Rust interface for the Limine Boot Protocol

[[bin]]
name = "nomad-second-stage"
path = "src/main.rs"
