[package]
name = "legal-guardian"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
regex = "1.10.3"
anyhow = "1.0"
colored = "2.0"
